spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      client:
        registration:
          vk:
            clientId: 52586325
            clientSecret: HPoUAuI5mWttqn6OeB6t
            authorization-grant-type: authorization_code
            scope: email
            redirectUri: "https://d492-95-104-189-149.ngrok-free.app/login/oauth2/code/vk"

        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: https://api.vk.com/method/users.get?fields=photo_200&access_token={token}&v=5.131
            user-name-attribute: id
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8443
  ssl:
    key-store: C:\Users\Dizaled/mykeys.jks
    key-store-password: Porfik 10
    key-password: Porfik 10

logging:
  file:
    path: /var/logs/
    file: TacoCloud.log
  level:
    org.springframework.security: DEBUG
taco:
  orders:
    page-size: 10

---
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      client:
        registration:
          taco-admin-client:
            provider: tacocloud
            client-id: taco-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9090/login/oauth2/code/{registrationId}"
            scope: writeIngredients,deleteIngredients,openid
        provider:
          tacocloud:
            issuer-uri: http://localhost:9000
            jwk-set-uri: http://localhost:9000/oauth2/jwks
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost/taco_cloud
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Porfik 10
  sql:
    init:
      mode: never
  logging:
    level:
      tacos: WARN
  data:
    rest:
      base-path: /data-api
  server:
    servlet:
      context-path: /data-api

